# Generated by Django 4.1.2 on 2022-11-15 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0002_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="product/product_cover",
                verbose_name="Product Image",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Comment Author",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.TextField(verbose_name="Comment Text"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="stars",
            field=models.CharField(
                choices=[
                    ("1", "Very Bad"),
                    ("2", "Bad"),
                    ("1", "Normal"),
                    ("1", "Good"),
                    ("1", "Perfect"),
                ],
                max_length=10,
                verbose_name="What is your score?",
            ),
        ),
    ]
